CREATE DATABASE IF NOT EXISTS DINH_HERNANDEZ;
use DINH_HERNANDEZ;

-- Create table of exemple
CREATE TABLE IF NOT EXISTS DINH_HERNANDEZ
(
    id INT NOT NULL AUTO_INCREMENT,
    uid VARCHAR(255) NOT NULL,
    url VARCHAR(1000) NOT NULL,
    PRIMARY KEY (id)
);
